---
permalink: api/reference_element_api_createinitiators.html 
sidebar: sidebar 
keywords: create,creating,initiator,CreateInitiators,WWPN,IQN,initiators 
summary: 您可以使用建立啟動器來建立多個新的啟動器IQN或全球連接埠名稱（WWPNs）、並選擇性地指派別名和屬性。當您使用建立啟動器建立新的啟動器時、也可以將其新增至磁碟區存取群組。 
---
= 建立啟動器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `CreateInitiators`建立多個新的啟動器 IQN 或全球連接埠名稱（ WWPN ）、並選擇性地指派別名和屬性。當您使用建立新的啟動器時 `CreateInitiators`、也可以將它們新增至 Volume 存取群組。

如果作業無法建立參數所提供的其中一個啟動器、則該方法會傳回錯誤、且不會建立任何啟動器（無法部分完成）。



== 參數

此方法具有下列輸入參數：

|===
| 名稱 | 說明 | 類型 | 預設值 | 必要 


 a| 
啟動器
 a| 
包含每個新啟動器特性的物件清單。物件：

* `alias`：（可選）要指派給此啟動器的易記名稱。（字串）
* `attributes`：（可選）一組 JSON 屬性，用於分配給此啓動器。（JSONN物件）
* `chapUsername`：（可選）此啓動器的唯一 CHAP 用戶名。如果在建立期間未指定啟動器名稱（IQN）、則預設為啟動器名稱（IQN）、且需求檢查為true。（字串）
* `initiatorSecret`：（可選）用於驗證啓動器的 CHAP 機密。如果在建立期間未指定、則預設為隨機產生的機密、且requireChap為true。（字串）
* `name`：（必填）要建立的啟動器名稱（ IQN 或 WWPN ）。（字串）
* `requireChap`：（可選）如果此啓動器的會話登錄過程中需要 CHAP ，則爲 True 。（布林值）
* `targetSecret`：（可選）用於驗證目標的 CHAP 機密（使用交互 CHAP 驗證時）。如果在建立期間未指定、則預設為隨機產生的機密、且requireChap為true。（字串）
* `virtualNetworkIDs`：（可選）與此啓動器關聯的虛擬網絡標識符列表。如果定義一個或多個虛擬網路、此啟動器只能登入這些虛擬網路。如果您未定義任何虛擬網路、此啟動器可以登入所有網路。
* `volumeAccessGroupID`：（可選）將添加此新創建的啓動器的卷訪問組的 ID 。（整數）

 a| 
Json物件陣列
 a| 
無
 a| 
是的

|===


== 傳回值

此方法具有下列傳回值：

|===


| 名稱 | 說明 | 類型 


 a| 
啟動器
 a| 
描述新建立之啟動器的物件清單。
 a| 
xref:reference_element_api_initiator.adoc[啟動器]陣列

|===


== 錯誤

此方法會傳回下列錯誤：

|===


| 名稱 | 說明 


 a| 
xinitialatorExis
 a| 
如果您選擇的啟動器名稱已經存在、則傳回。

|===


== 申請範例

此方法的要求類似於下列範例：

[listing]
----
{
  "id": 3291,
  "method": "CreateInitiators",
  "params": {
    "initiators": [
      {
        "name": "iqn.1993-08.org.debian:01:288170452",
        "alias": "example1"
      },
      {
        "name": "iqn.1993-08.org.debian:01:297817012",
        "alias": "example2"
      }
    ]
  }
}
----


== 回應範例

此方法會傳回類似下列範例的回應：

[listing]
----
{
  "id": 3291,
  "result": {
    "initiators": [
      {
        "alias": "example1",
        "attributes": {},
        "initiatorID": 145,
        "initiatorName": "iqn.1993-08.org.debian:01:288170452",
        "volumeAccessGroups": []
      },
      {
        "alias": "example2",
        "attributes": {},
        "initiatorID": 146,
        "initiatorName": "iqn.1993-08.org.debian:01:297817012",
        "volumeAccessGroups": []
      }
    ]
  }
}
----


== 新的自版本

9.6



== 如需詳細資訊、請參閱

xref:reference_element_api_listinitiators.adoc[清單啟動器]
