---
permalink: api/reference_element_api_modifyinitiators.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,initiators,initiator,attribute,attributes,modifyinitiators 
summary: 您可以使用ModifyInitiator方法來變更一或多個現有啟動器的屬性。 
---
= ModifyInitiator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用此 `ModifyInitiators`方法變更一或多個現有啟動器的屬性。

您無法變更現有啟動器的名稱。如果您需要變更啟動器的名稱、請先使用方法將其刪除、然後使用方法建立新的xref:reference_element_api_createinitiators.adoc[建立啟動器]名稱xref:reference_element_api_deleteinitiators.adoc[刪除啟動器]。

如果ModifyInitiator無法變更參數中所提供的其中一個啟動器、則該方法會傳回錯誤、且不會修改任何啟動器（無法部分完成）。



== 參數

此方法具有下列輸入參數：

|===


| 名稱 | 說明 | 類型 | 預設值 | 必要 


 a| 
啟動器
 a| 
包含每個要修改之啟動器特性的物件清單。可能的物件：

* `alias`：（可選）要分配給啓動器的新易記名稱。（字串）
* `attributes`：（可選）一組新的 JSON 屬性，用於分配給啓動器。（JSONN物件）
* `chapUsername`：（可選）此啓動器的新唯一 CHAP 用戶名。（字串）
* `forceDuringUpgrade`：在升級過程中完成啓動器修改。
* `initiatorID`：（必填）要修改的啟動器 ID 。（整數）
* `initiatorSecret`：（可選）用於驗證啓動器的新 CHAP 機密。（字串）
* `requireChap`：（可選） True （如果此啓動器需要 CHAP ）。（布林值）
* `targetSecret`：（可選）用於驗證目標的新 CHAP 機密（使用交互 CHAP 驗證時）。（字串）
* `virtualNetworkIDs`：（可選）與此啓動器關聯的虛擬網絡標識符列表。如果定義一個或多個虛擬網路、此啟動器只能登入這些虛擬網路。如果您未定義任何虛擬網路、此啟動器可以登入所有網路。
* `volumeAccessGroupID`：（可選）應將啓動器添加到的卷訪問組的 ID 。如果啟動器先前位於不同的Volume存取群組、則會從舊的Volume存取群組中移除。如果此金鑰存在但為null、則啟動器會從其目前的Volume存取群組中移除、但不會放置在任何新的Volume存取群組中。（整數）

 a| 
Json物件陣列
 a| 
無
 a| 
是的

|===


== 傳回值

此方法具有下列傳回值：

|===


| 名稱 | 說明 | 類型 


 a| 
啟動器
 a| 
描述新修改啟動器的物件清單。
 a| 
xref:reference_element_api_initiator.adoc[啟動器]陣列

|===


== 申請範例

此方法的要求類似於下列範例：

[listing]
----
{
  "id": 6683,
  "method": "ModifyInitiators",
  "params": {
    "initiators": [
      {
        "initiatorID": 2,
        "alias": "alias1",
        "volumeAccessGroupID": null
      },
      {
        "initiatorID": 3,
        "alias": "alias2",
        "volumeAccessGroupID": 1
      }
    ]
  }
}
----


== 回應範例

此方法會傳回類似下列範例的回應：

[listing]
----
{
  "id": 6683,
  "result": {
    "initiators": [
      {
        "alias": "alias1",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:395543635",
        "volumeAccessGroups": []
      },
      {
        "alias": "alias2",
        "attributes": {},
        "initiatorID": 3,
        "initiatorName": "iqn.1993-08.org.debian:01:935573135",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== 新的自版本

9.6



== 如需詳細資訊、請參閱

* xref:reference_element_api_createinitiators.adoc[建立啟動器]
* xref:reference_element_api_deleteinitiators.adoc[刪除啟動器]

